apiVersion: 1

contactPoints:
  - orgId: 1
    name: PARUT Discord
    receivers:
      - uid: parut-discord
        type: discord
        disableResolveMessage: false
        settings:
          url: $DISCORD_WEBHOOK_URL
